name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: '发布类型 (patch/minor/major)'
        required: true
        default: 'patch'
  push:
    branches:
      - '*'
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.github/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 或更高版本，如 '18'
      
      - name: Configure Git
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"
      
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run release script
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            npm run release -- ${{ github.event.inputs.releaseType }}
          else
            npm run release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Push changes
        run: |
          git pull --rebase origin ${{ github.ref }}
          git push --follow-tags
          git push origin --tags
      
      - name: Display error log
        if: failure()
        run: cat /home/runner/.npm/_logs/*-debug.log