on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run package
    
    - name: List files in release directory
      run: ls -R release
    
    - name: List release directory contents
      run: |
        ls -la ./release
        echo "Current working directory: $(pwd)"
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release create ${{ github.ref_name }} \
          --generate-notes \
          --draft
    
    - name: Upload Release Asset
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        zip_file=$(ls ./release/markdown-master-*.zip | head -n 1)
        if [ -f "$zip_file" ]; then
          gh release upload ${{ github.ref_name }} "$zip_file" --clobber
        else
          echo "ZIP file not found in release directory"
          exit 1
        fi
    
    - name: Publish Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release edit ${{ github.ref_name }} --draft=false