name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: '发布类型 (patch/minor/major)'
        required: true
        default: 'patch'
  push:
    branches:
      - '*'  # 匹配所有分支
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.github/**'

jobs:
  check_commit_message:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.check_message.outputs.release }}
    steps:
      - uses: actions/checkout@v2
      - name: Check commit message
        id: check_message
        run: |
          message=$(git log --format=%B -n 1 ${{ github.event.after }})
          if [[ $message == *"[release]"* ]]; then
            echo "::set-output name=release::true"
          else
            echo "::set-output name=release::false"
          fi

  release:
    needs: check_commit_message
    if: github.event_name == 'workflow_dispatch' || needs.check_commit_message.outputs.release == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Release
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            npm run release -- ${{ github.event.inputs.releaseType }}
          else
            npm run release
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}