- name: Create Release
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
run: |
  gh release create ${{ github.ref }} \
    --draft \
    --title "Release ${{ github.ref_name }}" \
    --generate-notes \
    build/main.js manifest.json styles.css