name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: markdown-master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build plugin
      run: |
        npm install
        npm run build

    - name: Create release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag="${GITHUB_REF#refs/tags/}"
        
        # 创建发布文件夹
        mkdir ${{ env.PLUGIN_NAME }}
        cp main.js manifest.json styles.css ${{ env.PLUGIN_NAME }}
        zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
        
        # 创建 release
        gh release create "$tag" \
          --title="$tag" \
          --draft

        # 只上传 zip 文件
        gh release upload "$tag" ${{ env.PLUGIN_NAME }}.zip

    - name: Publish release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag="${GITHUB_REF#refs/tags/}"
        gh release edit "$tag" --draft=false